import { Vacancy } from '@/shared/types/vacancy';

export const mockVacancies: Vacancy[] = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    company: 'TechCorp',
    location: 'Moscow',
    salary: { min: 250000, max: 350000, currency: 'RUB' },
    status: 'open',
    department: 'Engineering',
    createdAt: '2024-01-15',
    linkedVacancies: ['2', '5'],
    applicantsCount: 24,
  },
  {
    id: '2',
    title: 'Frontend Developer',
    company: 'TechCorp',
    location: 'Moscow',
    salary: { min: 150000, max: 220000, currency: 'RUB' },
    status: 'open',
    department: 'Engineering',
    createdAt: '2024-01-18',
    linkedVacancies: ['1'],
    applicantsCount: 45,
  },
  {
    id: '3',
    title: 'Product Manager',
    company: 'StartupX',
    location: 'Saint Petersburg',
    salary: { min: 200000, max: 300000, currency: 'RUB' },
    status: 'paused',
    department: 'Product',
    createdAt: '2024-01-10',
    linkedVacancies: [],
    applicantsCount: 12,
  },
  {
    id: '4',
    title: 'UX Designer',
    company: 'DesignHub',
    location: 'Remote',
    salary: { min: 180000, max: 250000, currency: 'RUB' },
    status: 'open',
    department: 'Design',
    createdAt: '2024-01-20',
    linkedVacancies: ['6'],
    applicantsCount: 31,
  },
  {
    id: '5',
    title: 'Backend Developer',
    company: 'TechCorp',
    location: 'Moscow',
    salary: { min: 280000, max: 400000, currency: 'RUB' },
    status: 'open',
    department: 'Engineering',
    createdAt: '2024-01-12',
    linkedVacancies: ['1', '2'],
    applicantsCount: 18,
  },
  {
    id: '6',
    title: 'UI Designer',
    company: 'DesignHub',
    location: 'Remote',
    salary: { min: 160000, max: 230000, currency: 'RUB' },
    status: 'closed',
    department: 'Design',
    createdAt: '2024-01-05',
    linkedVacancies: ['4'],
    applicantsCount: 52,
  },
  {
    id: '7',
    title: 'DevOps Engineer',
    company: 'CloudSystems',
    location: 'Kazan',
    salary: { min: 220000, max: 320000, currency: 'RUB' },
    status: 'draft',
    department: 'Engineering',
    createdAt: '2024-01-22',
    linkedVacancies: [],
    applicantsCount: 0,
  },
  {
    id: '8',
    title: 'HR Manager',
    company: 'PeopleFirst',
    location: 'Novosibirsk',
    salary: { min: 120000, max: 180000, currency: 'RUB' },
    status: 'open',
    department: 'HR',
    createdAt: '2024-01-08',
    linkedVacancies: [],
    applicantsCount: 8,
  },
];

export const locations = ['All', 'Moscow', 'Saint Petersburg', 'Remote', 'Kazan', 'Novosibirsk'];
export const departments = ['All', 'Engineering', 'Product', 'Design', 'HR'];
