import { Vacancy, IEntityBasic, IUser } from '@/shared/types/vacancy';

const clients: IEntityBasic[] = [
  { id: 'c1', name: 'TechCorp' },
  { id: 'c2', name: 'StartupX' },
  { id: 'c3', name: 'DesignHub' },
  { id: 'c4', name: 'CloudSystems' },
  { id: 'c5', name: 'PeopleFirst' },
];

const recruiters: (IUser & { isActive: boolean })[] = [
  { id: 'r1', firstName: 'Anna', lastName: 'Ivanova', email: 'anna@example.com', isActive: true },
  { id: 'r2', firstName: 'John', lastName: 'Doe', email: 'john@example.com', isActive: true },
];

const atsStatuses: IEntityBasic[] = [
  { id: 's1', name: 'Open' },
  { id: 's2', name: 'Closed' },
  { id: 's3', name: 'On Hold' },
];

const postingStatuses: IEntityBasic[] = [
  { id: 'p1', name: 'Published' },
  { id: 'p2', name: 'Draft' },
  { id: 'p3', name: 'Archived' },
];

const countries: IEntityBasic[] = [
  { id: 'cnt1', name: 'Russia' },
  { id: 'cnt2', name: 'USA' },
];

const cities: IEntityBasic[] = [
  { id: 'ct1', name: 'Moscow' },
  { id: 'ct2', name: 'Saint Petersburg' },
  { id: 'ct3', name: 'New York' },
  { id: 'ct4', name: 'Kazan' },
  { id: 'ct5', name: 'Novosibirsk' },
];

export const mockVacancies: Vacancy[] = [
  {
    id: '1',
    atsId: 'ATS-001',
    title: 'Senior Frontend Developer',
    mainJbUrl: 'https://example.com/jobs/1',
    isRepeating: false,
    comment: 'Urgent hiring',
    specificProject: 'Core Platform',
    mainJbPosted: '2024-01-15T10:00:00Z',
    isPosted: true,
    dateCreated: '2024-01-10T09:00:00Z',
    isMain: true,
    linkedIds: ['2', '5'],
    client: clients[0],
    recruiter: recruiters[0],
    atsStatus: atsStatuses[0],
    postingStatus: postingStatuses[0],
    country: countries[0],
    city: cities[0],
  },
  {
    id: '2',
    atsId: 'ATS-002',
    title: 'Frontend Developer',
    mainJbUrl: null,
    isRepeating: false,
    comment: null,
    specificProject: 'Core Platform',
    mainJbPosted: '2024-01-18T10:00:00Z',
    isPosted: true,
    dateCreated: '2024-01-12T09:00:00Z',
    isMain: false,
    linkedIds: ['1'],
    client: clients[0],
    recruiter: recruiters[1],
    atsStatus: atsStatuses[0],
    postingStatus: postingStatuses[0],
    country: countries[0],
    city: cities[0],
  },
  {
    id: '3',
    atsId: 'ATS-003',
    title: 'Product Manager',
    mainJbUrl: 'https://example.com/jobs/3',
    isRepeating: true,
    comment: 'Replacement',
    specificProject: 'Mobile App',
    mainJbPosted: '2024-01-10T10:00:00Z',
    isPosted: false,
    dateCreated: '2024-01-05T09:00:00Z',
    isMain: true,
    linkedIds: [],
    client: clients[1],
    recruiter: recruiters[0],
    atsStatus: atsStatuses[2],
    postingStatus: postingStatuses[1],
    country: countries[0],
    city: cities[1],
  },
  {
    id: '4',
    atsId: 'ATS-004',
    title: 'UX Designer',
    mainJbUrl: 'https://example.com/jobs/4',
    isRepeating: false,
    comment: null,
    specificProject: 'Design System',
    mainJbPosted: '2024-01-20T10:00:00Z',
    isPosted: true,
    dateCreated: '2024-01-15T09:00:00Z',
    isMain: true,
    linkedIds: ['6'],
    client: clients[2],
    recruiter: recruiters[1],
    atsStatus: atsStatuses[0],
    postingStatus: postingStatuses[0],
    country: countries[1],
    city: cities[2],
  },
  {
    id: '5',
    atsId: 'ATS-005',
    title: 'Backend Developer',
    mainJbUrl: null,
    isRepeating: false,
    comment: null,
    specificProject: 'API Gateway',
    mainJbPosted: '2024-01-12T10:00:00Z',
    isPosted: true,
    dateCreated: '2024-01-08T09:00:00Z',
    isMain: false,
    linkedIds: ['1', '2'],
    client: clients[0],
    recruiter: recruiters[0],
    atsStatus: atsStatuses[0],
    postingStatus: postingStatuses[0],
    country: countries[0],
    city: cities[0],
  },
  {
    id: '6',
    atsId: 'ATS-006',
    title: 'UI Designer',
    mainJbUrl: null,
    isRepeating: false,
    comment: null,
    specificProject: 'Design System',
    mainJbPosted: '2024-01-05T10:00:00Z',
    isPosted: false,
    dateCreated: '2024-01-02T09:00:00Z',
    isMain: false,
    linkedIds: ['4'],
    client: clients[2],
    recruiter: recruiters[1],
    atsStatus: atsStatuses[1],
    postingStatus: postingStatuses[2],
    country: countries[1],
    city: cities[2],
  },
  {
    id: '7',
    atsId: 'ATS-007',
    title: 'DevOps Engineer',
    mainJbUrl: null,
    isRepeating: false,
    comment: 'New position',
    specificProject: 'Infrastructure',
    mainJbPosted: '2024-01-22T10:00:00Z',
    isPosted: false,
    dateCreated: '2024-01-20T09:00:00Z',
    isMain: true,
    linkedIds: [],
    client: clients[3],
    recruiter: recruiters[0],
    atsStatus: atsStatuses[0],
    postingStatus: postingStatuses[1],
    country: countries[0],
    city: cities[3],
  },
  {
    id: '8',
    atsId: 'ATS-008',
    title: 'HR Manager',
    mainJbUrl: 'https://example.com/jobs/8',
    isRepeating: false,
    comment: null,
    specificProject: 'Internal',
    mainJbPosted: '2024-01-08T10:00:00Z',
    isPosted: true,
    dateCreated: '2024-01-05T09:00:00Z',
    isMain: true,
    linkedIds: [],
    client: clients[4],
    recruiter: recruiters[1],
    atsStatus: atsStatuses[0],
    postingStatus: postingStatuses[0],
    country: countries[0],
    city: cities[4],
  },
];

export const mockClients = clients;
export const mockRecruiters = recruiters;
export const mockAtsStatuses = atsStatuses;
export const mockPostingStatuses = postingStatuses;
export const mockCountries = countries;
export const mockCities = cities;
